### ISSUE TITLE
Add mayavi to binder

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-binder#2]
I was wondering if there is interest in having this binder output mayavi screenshot images.

I was hoping this could be done using xvfb + mlab.options.offscreen = True

It would allow MNE to have binder links in examples using sphinx gallery

Here's what I tried so far:

```sh
# Binder Docker config file.

# This is required
FROM andrewosh/binder-base
MAINTAINER Mainak Jas <mainakjas@gmail.com>

USER root

# get xvfb for mayavi headless mode
# https://stackoverflow.com/questions/55387506/how-to-fix-failed-to-fetch-debian-jessie-updates-issue-on-docker
RUN sed -i '/jessie-updates/d' /etc/apt/sources.list
RUN apt-get update && apt-get install --fix-missing -y xvfb

# needed for mayavi to work
# https://github.com/conda-forge/pygridgen-feedstock/issues/10
RUN apt install libgl1-mesa-glx

# Install dependencies and MNE master
RUN conda update conda; 

RUN conda install --yes numpy scipy matplotlib mayavi

RUN pip install xvfbwrapper mne

```

Unfortunately, I just keep getting "kernel died". Any help would be welcome :-)

**Comment by jasmainak** [comment]
okay I got a little further by adding this to the start of my notebooks:

```py
import os
os.environ['ETS_TOOLKIT']='null'

from IPython.display import Image
from mayavi import mlab

mlab.options.offscreen = True

from xvfbwrapper import Xvfb
display = Xvfb(width=1920, height=1080)
display.start()
```

plot_alignment works but not stc.plot ... see [here](https://mybinder.org/v2/gh/jasmainak/mne-workshop-brown/gh-pages?filepath=content%2Fevoked_to_stc%2Fforward.ipynb) for demo

**Comment by kingjr** [comment]
Shouldnt we use https://github.com/mne-tools/mne-gsoc2018-3d instead?

**Comment by jasmainak** [comment]
hmm ... good point. But it won't work for plot_alignment etc, no? I'll give it a shot anyway.

I guess what would then be missing is that plot_alignment would not work with that, so I'll need to use a mix of mayavi and ipysurfer

**Comment by larsoner** [comment]
Someone should try this

https://docs.enthought.com/mayavi/mayavi/tips.html#using-mayavi-in-jupyter-notebooks

**Comment by jasmainak** [comment]
That works nicely but only when I try on my own computer. The problem is that I can't even import mlab when I'm in headless mode in a notebook

EDIT: The issue with the import is that the kernel just dies which probably means mayavi is trying to do some access of display during the import.

EDIT2: That's why setting os.environ['ETS_TOOLKIT']='null' allowed me to do the import and that made plot_alignment work, but then stc.plot does not work if you do that

**Comment by kingjr** [comment]
"The images are static and one cannot interact with them"
the future ;)

**Comment by larsoner** [comment]
> "The images are static and one cannot interact with them"

Well the fuller quote is:

> Mayavi can display either images or X3D elements on the notebook. The images are static and one cannot interact with them. The X3D output produces a fully interactive 3D scene.

And later:

>  One can call init_notebook multiple times if one wishes to change the backend between png and x3d for some reason.

I think they mean that there are two modes, image and X3D mode / backend for the notebook. The X3D mode rather than image mode is the one I'm more interested in.

Coming back to xvfb, you'll need it configured properly to support OpenGL. I doubt the `ETS_TOOLKIT`='null'` approach will work for plotting. We don't need it on our CIs, they use software GL rendering.

Before dealing with Python at all I'd work to get the system to tolerate running `glxgears` or some other simple OpenGL program after running `xvfb` directly, e.g.:
```
$ /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset
$ export DISPLAY=:99
$ glxgears
```
If this works then move on to something like
```
$ LIBGL_DEBUG=verbose python -ic "from mayavi import mlab; mlab.test_plot3d()"
```
You can see what we install and how we run `xvfb` in the PySurfer or MNE travis or circleci configs. You probably need to install the software rendering driver `libosmesa6`.

**Comment by kingjr** [comment]
my bad thx

**Comment by jasmainak** [comment]
Thanks a lot @larsoner for the suggestions! Will give it a shot.

I'm ccing @mirestrepo who is helping me assemble this for an MNE workshop at Brown, in case there are any more questions from her end.

**Comment by mirestrepo** [comment]
@jasmainak instead of using xvfbwrapper you can start the server at the entry point of the docker container by adding 
```
ENTRYPOINT ["tini", "-g", "--", "xvfb-run"]
```
or maybe even
 ```
ENTRYPOINT [ "xvfb-run"]
```

See https://github.com/brown-ccv/docker-stacks/blob/master/jupyterhub/mne/Dockerfile

My docker image only works with the png backend and is still missing to handle OpenGL for the x3d backend... Maybe adding the GLX extensions as @larsoner suggested could do the trick....

**Comment by jasmainak** [comment]
Thanks for the suggestion @mirestrepo ! The dockerfile runs like a charm. 

However, there is still one fix needed to make it work on mybinder. I need to add an additional command right before the ENTRYPOINT to clone the repository. I'm not exactly sure what's going on, but could it be that one of your commands is removing the contents of the current directory?

**Comment by mirestrepo** [comment]
My docker image never copies the contents of the local directory. For jupyterhub, the code is not part of the docker image because all changes would then be ephemeral... so it makes sense that you would need to change it in you case to copy the contents of the directory

**Comment by wmvanvliet** [comment]
as of mayavi 4.7.0, the `ipy` backend is supported, finally bringing full remote rendering support to mayavi. Check it out [here in binder](https://mybinder.org/v2/gh/wmvanvliet/SNL_workshop_2019/master?filepath=SNL_workshop_2019.ipynb) and the [Dockerfile](https://github.com/wmvanvliet/snl_workshop_2019/blob/master/Dockerfile) that is powering this.

**Comment by agramfort** [comment]
it's not interactive right?

**Comment by larsoner** [comment]
I ran the binder link @wmvanvliet posted and after changing `mlab.init_notebook('png')` to `mlab.init_notebook('ipy')` the four plots are interactive 😲:

![Screenshot from 2019-07-10 11-05-06](https://user-images.githubusercontent.com/2365790/60980528-a7ae7080-a302-11e9-95f4-f757c9020a4f.png)

The four plots in this case all show the same thing, and dragging one drags all of them, but this is already great progress!

**Comment by jasmainak** [comment]
That is amazing! Should we update the Dockerfile on this repo @wmvanvliet ? The one here is super outdated.

**Comment by agramfort** [comment]
works for me too !

>

**Comment by wmvanvliet** [comment]
Yeah sorry, the binder link points to the wrong notebook in the repo. But you got there in the end.

**Comment by wmvanvliet** [comment]
> That is amazing! Should we update the Dockerfile on this repo @wmvanvliet? The one here is super outdated.

I think we should :) You may want to change some things, like checking out the latest master instead of latest release of MNE-Python. And maybe doing some `python -c 'import ...'` things to "precompile" the python module for faster subsequent access.

But the mayavi integration (based on your Dockerfile @jasmainak) works great!

**Comment by jasmainak** [comment]
yes! let's do it :)

**Comment by christianhacker** [comment]
Know this is closed, but I'd like to know how to use the Dockerfile to run a container under Docker Desktop (W10). I was able to build the image, but the container fails because a command isn't passed to `xvfb-run`. Any suggestions?

**Comment by jasmainak** [comment]
did you try the ENTRYPOINT trick [mentioned above](https://github.com/mne-tools/mne-binder/issues/2#issuecomment-479914530)

**Comment by christianhacker** [comment]
I actually got it working, forgot to pass a Docker a command to run. Just passed `jupyter notebook` and it started right up. Now the challenge is getting `x3d` or `ipy` rendering working in jupyterlab...
