### ISSUE TITLE
Binder fails to launch

### ISSUE THREAD

**Issue by rob-luke** [mne-tools/mne-binder#6]
The link in the README fails to launch with the error...

```
ERROR: Could not find a version that satisfies the requirement PIL (from versions: none)
ERROR: No matching distribution found for PIL
```

I will dig in to this in the coming days.

**Comment by larsoner** [comment]
Probably just need to kill this line:

https://github.com/mne-tools/mne-binder/blob/master/Dockerfile#L43

I don't see a reason to try installing both `PIL` and `pillow`, they are designed to provide the same functionality, but `pillow` is the newer/preferred one
